# Generated by Django 4.1.7 on 2023-02-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230, verbose_name='Title')),
                ('image', models.ImageField(upload_to='book/images/')),
                ('pdf', models.FileField(upload_to='book/pdf/')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('description', models.CharField(max_length=250)),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN number')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa wydawnictwa', max_length=60)),
                ('adres', models.CharField(help_text='Adres internetowy wydawnictwa', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='tag', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('EDITOR', 'Editor'), ('REVIEWER', 'Reviewer')], max_length=20, verbose_name='Rola jaką współtwórca odegrał przy tworzeniu książki')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='main.BookContributor', to='main.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tag'),
        ),
    ]
