# Generated by Django 4.1.7 on 2023-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='english', max_length=20, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='', max_length=230, verbose_name='Subtitle'),
        ),
    ]
