# Generated by Django 4.1.7 on 2023-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_language_book_pages_book_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, upload_to='book/pdf/'),
        ),
    ]
