# Generated by Django 4.1.7 on 2023-03-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_author_remove_book_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='', max_length=20, verbose_name='Language'),
        ),
    ]
