# Generated by Django 4.1.7 on 2023-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booklanguage_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='my_file_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
