# Generated by Django 4.1.7 on 2023-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_translator_book_translators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=230, verbose_name='Subtitle'),
        ),
    ]
