# Generated by Django 4.1.7 on 2023-04-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
