# Generated by Django 4.1.7 on 2023-04-10 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UsersBookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READ', 'Read'), ('IN_PROGRESS', 'In progress'), ('POSTPONED', 'Postponed'), ('TO_READ', 'To read'), ('INTERESTING', 'Interesting'), ('NOT_INTERESTING', 'Not interesting')], max_length=20, verbose_name='Status przerobienia książki przez użytkownika')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userbooks')),
            ],
        ),
        migrations.AddField(
            model_name='userbooks',
            name='books',
            field=models.ManyToManyField(through='main.UsersBookStatus', to='main.book'),
        ),
        migrations.AddField(
            model_name='userbooks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
